---
title: "Electricity Prices"
author: "CAKU"
date: "`r Sys.Date()`"
output: html_document
---

# East Denmark
 
```{r echo=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
library(pacman)
pacman::p_load(tidyr,
               dplyr,
               ggplot2,
               httr,
               rpart.plot,
               pushoverr,
               caret,
               zoo,
               glue,
               rPref,
               lubridate)
```

```{r warning=FALSE,message=FALSE,include=FALSE}
readRenviron(path = "Renviron.site")
pushoverr::set_pushover_app(token = Sys.getenv("PUSHOVER_APPKEY"))
pushoverr::set_pushover_user(user = Sys.getenv("PUSHOVER_USERKEY"))

```


```{r}

# api_url = 'https://api.energidataservice.dk/datastore_search_sql?sql=SELECT "HourDK","SpotPriceDKK","SpotPriceEUR" FROM "elspotprices" WHERE "PriceArea"=\'DK2\' ORDER BY "HourDK" DESC LIMIT 30000'
# api_url = "https://api.energidataservice.dk/dataset/Elspotprices?offset=0&filter=%7B%22PriceArea%22:[%22DK2%22]%7D&sort=HourUTC%20DESC&timezone=dk&limit=35000"
api_url = "https://api.energidataservice.dk/dataset/Elspotprices?offset=0&sort=HourUTC%20DESC&timezone=dk&limit=50000"


api_url = utils::URLencode(api_url)
api_result = httr::GET(api_url)
api_json = rawToChar(api_result$content)
df <- jsonlite::fromJSON(api_json)$records
df = df %>% 
  filter(PriceArea=="DK2") %>% 
  dplyr::mutate(HourDK=ymd_hms(HourDK,tz = "Europe/Copenhagen"),
                SpotPriceDKK=SpotPriceDKK/1000,
                SpotPriceEUR=SpotPriceEUR/1000) %>% 
  dplyr::mutate(ExchangeRate=SpotPriceDKK/SpotPriceEUR) %>% 
  dplyr::mutate(SpotPriceDKK=ifelse(is.na(SpotPriceDKK),SpotPriceEUR*7.43988,SpotPriceDKK)) %>% 
  # Radius nettarif per 30. september 2023, moms 20%, afgift 87.13 ører.
  dplyr::mutate(transport=case_when(month(HourDK) %in% seq(4,9,by=1) & hour(HourDK) %in% seq(0,5,by=1)~12.20,
                                    month(HourDK) %in% seq(4,9,by=1) & hour(HourDK) %in% seq(6,16,by=1)~18.31,
                                    month(HourDK) %in% seq(4,9,by=1) & hour(HourDK) %in% seq(17,20,by=1)~47.60,
                                    month(HourDK) %in% seq(4,9,by=1) & hour(HourDK) %in% seq(21,23,by=1)~18.31,
                                    month(HourDK) %in% c(1,2,3,10,11,12) & hour(HourDK) %in% seq(0,5,by=1)~12.20,
                                    month(HourDK) %in% c(1,2,3,10,11,12) & hour(HourDK) %in% seq(6,16,by=1)~36.61,
                                    month(HourDK) %in% c(1,2,3,10,11,12) & hour(HourDK) %in% seq(17,20,by=1)~109.85,
                                    month(HourDK) %in% c(1,2,3,10,11,12) & hour(HourDK) %in% seq(21,23,by=1)~36.61,
                TRUE~as.numeric(NA))) %>% 
  dplyr::mutate(transport=transport*0.8) %>%  # uden moms
  dplyr::mutate(elafgift=72.00) %>% 
  dplyr::mutate(SpotPriceDKK_Total=1.25*(SpotPriceDKK+transport/100+elafgift/100)) %>% 
  dplyr::mutate(SpotPriceDKK_Total_SansAfgift=1.25*(SpotPriceDKK+transport/100)) %>% 
  dplyr::mutate(SpotPriceDKK_Total_SansAfgiftTransport=1.25*(SpotPriceDKK/100))
```


## Best Upcoming

```{r}

df_previous = df %>% 
  dplyr::mutate(Day=wday(HourDK,label=TRUE,abbr=FALSE),
                Hour=hour(HourDK)) %>% 
  dplyr::mutate(Day=factor(Day)) %>% 
  dplyr::select(Day,
                Hour,
                SpotPriceDKK_Total_SansAfgift)

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = Sys.time()

lwr_upr = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(SpotPriceDKK_z=scale(SpotPriceDKK_Total)) %>% 
  filter(SpotPriceDKK_z<=0) %>% 
  dplyr::mutate(Cheap="Cheap")

p1 = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day=wday(HourDK,label=TRUE,abbr=FALSE)) %>% 
  dplyr::mutate(HourDK=hour(HourDK)) %>% 
  dplyr::mutate(Day=factor(Day)) %>% 
  ggplot(.,aes(x=HourDK,y=SpotPriceDKK_Total_SansAfgift,color=Day)) +
  geom_line(size=3) +
  # geom_line(data=lwr_upr,aes(x=HourDK,y=SpotPriceDKK_Total,color=Cheap),size=2) +
  geom_line(aes(x=HourDK,y=SpotPriceDKK_Total),linetype=2) +
  # geom_line(aes(x=HourDK,y=SpotPriceDKK_Total_SansAfgiftTransport),linetype=4) +
  geom_hline(yintercept = 0) +
  # scale_x_datetime(date_breaks = "1 hour",date_labels = "%H") +
  scale_y_continuous(limits=c(-0.5,NA),breaks = seq(-1,10,by=0.25)) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  # geom_vline(xintercept = Sys.time(),linetype=2,alpha=0.7)  +
  labs(title="Lowest Upcoming Prices",
       subtitle="East Denmark",
       x="Hour",
       y="Price (DKK)") +
  # theme(legend.position="null") +
  geom_smooth(data=df_previous,aes(x=Hour,y=SpotPriceDKK_Total_SansAfgift,linetype=Day),alpha=0,size=0.4)
p1

```

## Best Upcoming, All Day

```{r}

lwr_upr = df %>% 
  filter(HourDK >= Sys.time()) %>% 
  dplyr::mutate(SpotPriceDKK_z=scale(SpotPriceDKK_Total)) %>% 
  filter(SpotPriceDKK_z<=0) %>% 
  dplyr::mutate(Cheap="Cheap")

p2 = df %>% 
  filter(HourDK >= Sys.time()) %>% 
  ggplot(.,aes(x=HourDK,y=SpotPriceDKK_Total)) +
  geom_line() +
  # geom_line(data=lwr_upr,aes(x=HourDK,y=SpotPriceDKK_Total,color=Cheap),size=2) +
  geom_line(aes(x=HourDK,y=SpotPriceDKK_Total_SansAfgift),linetype=3) +
  geom_line(aes(x=HourDK,y=SpotPriceDKK_Total_SansAfgiftTransport),linetype=4) +
  # geom_hline(yintercept = 0) +
  scale_x_datetime(date_breaks = "1 hour",date_labels = "%H") +
  scale_y_continuous(limits=c(-0.5,NA),breaks = seq(-1,10,by=0.25)) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  # geom_vline(xintercept = Sys.time(),linetype=2,alpha=0.7)  +
  labs(title="Lowest Upcoming Prices",
       subtitle="East Denmark",
       x="Hour",
       y="Price (DKK)") +
  theme(legend.position="null")
p2

```
## Best Two-Hour Window

```{r}
max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = Sys.time()

max_forecast_day

mean_sd = df %>% 
  filter(as.Date(HourDK)>=Sys.Date()-days(30)) %>% 
    filter(hour(HourDK) >= 6) %>% 
    filter(hour(HourDK) <= 17) %>% 
  dplyr::summarize(mean_=mean(SpotPriceDKK_Total_SansAfgift),sd_=sd(SpotPriceDKK_Total_SansAfgift))

df_windows = lapply(seq(2,5),function(window) {
  
  df %>% 
    filter(HourDK >= max_forecast_day) %>% 
    # filter(hour(HourDK) >= 6) %>% 
    # filter(hour(HourDK) <= 17) %>% 
    arrange(HourDK) %>% 
    dplyr::mutate(rollingsum=zoo::rollsum(x = SpotPriceDKK_Total_SansAfgift,k = window,fill = NA,align = "left"),
    # dplyr::mutate(rollingsum=zoo::rollsum(x = SpotPriceDKK_Total,k = window,fill = NA,align = "left"),
                  window=window) %>% 
    dplyr::mutate(rollingsum=rollingsum/window) %>% 
    dplyr::mutate(p_norm=pnorm(rollingsum,mean=mean_sd$mean_,sd=mean_sd$sd_)) %>% 
  dplyr::mutate(p_label=scales::percent(p_norm,accuracy=1)) %>% 
    na.omit
  
})
df_windows = do.call("rbind",df_windows)

# Consider again the preference from above
p <- low(rollingsum) * high(window)

# Calculate the level-value w.r.t. p by using top-all
res <- psel(df_windows, p, top = nrow(df_windows)) %>% filter(.level==min(.level))
res %>% 
  dplyr::select(HourDK,.level,rollingsum,window,p_norm) %>% 
  knitr::kable()


```


## Best Two-Hour Window, All Day

```{r}

mean_sd = df %>% 
  filter(as.Date(HourDK)>=Sys.Date()-days(30)) %>% 
    # filter(hour(HourDK) >= 6) %>% 
    # filter(hour(HourDK) <= 17) %>% 
  dplyr::summarize(mean_=mean(SpotPriceDKK_Total_SansAfgift),sd_=sd(SpotPriceDKK_Total_SansAfgift))

df_windows = lapply(seq(2,5),function(window) {
  
  look_up = data.frame(pct=seq(0,1,by=0.01),
           value = df %>% 
    filter(as.Date(HourDK)>=Sys.Date()-days(30)) %>% 
    arrange(HourDK) %>% 
    dplyr::mutate(rollingsum=zoo::rollsum(x = SpotPriceDKK_Total_SansAfgift,k = window,fill = NA,align = "left"),
                  window=window) %>% 
    dplyr::mutate(rollingsum=rollingsum/window)  %>% 
    pull(rollingsum) %>% 
    quantile(.,seq(0,1,by=0.01),na.rm=T))
  
  df %>% 
    filter(HourDK >= Sys.time()) %>% 
    # filter(hour(HourDK) >= 6) %>% 
    # filter(hour(HourDK) <= 17) %>% 
    arrange(HourDK) %>% 
    dplyr::mutate(rollingsum=zoo::rollsum(x = SpotPriceDKK_Total_SansAfgift,k = window,fill = NA,align = "left"),
                  window=window) %>% 
    dplyr::mutate(rollingsum=rollingsum/window) %>% 
    filter(rollingsum==min(rollingsum,na.rm=T)) %>% 
    # dplyr::mutate(p_norm=pnorm(rollingsum,mean=mean_sd$mean_,sd=mean_sd$sd_)) %>% 
    tidyr::crossing(look_up) %>% 
    filter(rollingsum>=value) %>% 
    filter(pct==max(pct)) %>% 
    dplyr::mutate(p_label=scales::percent(pct,accuracy=1)) %>% 
    na.omit
  
})
df_windows = do.call("rbind",df_windows)

# Consider again the preference from above
p <- low(rollingsum) * high(window)

# Calculate the level-value w.r.t. p by using top-all
res_2 <- psel(df_windows, p, top = nrow(df_windows)) %>% filter(.level==min(.level))
res_2 %>% 
  dplyr::select(HourDK,.level,rollingsum,window,pct) %>% 
  knitr::kable()


```

```{r}
lwr_upr = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(SpotPriceDKK_z=scale(SpotPriceDKK_Total)) %>% 
  filter(SpotPriceDKK_z<=0) %>% 
  dplyr::mutate(Cheap="Cheap")

df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  ggplot(.,aes(x=HourDK,y=SpotPriceDKK_Total)) +
  geom_line() +
  # geom_line(data=lwr_upr,aes(x=HourDK,y=SpotPriceDKK_Total,color=Cheap),size=2) +
  geom_line(aes(x=HourDK,y=SpotPriceDKK_Total_SansAfgift),linetype=3) +
  # geom_hline(yintercept = 0) +
  scale_y_continuous(limits=c(-1,NA),breaks = seq(-1,10,by=0.25)) +
  scale_x_datetime(date_breaks = "1 hour",date_labels = "%H") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  # geom_vline(xintercept = Sys.time(),linetype=2,alpha=0.7)  +
  labs(title="Lowest Upcoming Prices",
       subtitle="East Denmark",
       x="Hour",
       y="Price (DKK)") +
  theme(legend.position="null")


```
## Last Week & Upcoming

```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-days(7)

df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  ggplot(.,aes(x=Day_Num,y=Hour)) +
  geom_tile(aes(fill=SpotPriceDKK_Total)) +
  scale_fill_gradient(low = "green",high = "red") +
  scale_x_datetime(date_breaks = "1 day",date_labels = "%a %b %d") +
  scale_y_continuous(breaks = seq(0,23,by=1),labels = paste0(seq(0,23,by=1)," - ",seq(1,24,by=1))) +
  theme_bw() +
  geom_text(aes(label=scales::number(SpotPriceDKK_Total,accuracy = 0.01)))  +
  labs(title="Previous Week and Upcoming Prices",
       subtitle="East Denmark",
       x="Day",
       y="Hour") +
  theme(legend.position="null")
```


```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-days(7)

lwr_upr = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(SpotPriceDKK_z=scale(SpotPriceDKK_Total_SansAfgift)) %>% 
  filter(SpotPriceDKK_z<=qnorm(p = 0.975) | SpotPriceDKK_z<=qnorm(p = 0.025)) %>% 
  dplyr::summarise(lwr=min(SpotPriceDKK_Total_SansAfgift),upr=max(SpotPriceDKK_Total_SansAfgift))

lwr_upr_date = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::summarise(lwr=min(HourDK),upr=max(HourDK))


df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  ggplot(.,aes(x=HourDK,y=SpotPriceDKK_Total_SansAfgift)) +
  geom_line() +
  geom_line(aes(x=HourDK,y=SpotPriceDKK_Total_SansAfgift),linetype=3) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits=c(-1,NA),breaks = seq(-1,10,by=0.25)) +
  scale_x_datetime(date_breaks = "1 day",date_labels = "%d") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  geom_vline(xintercept = Sys.time(),linetype=2,alpha=0.7) +
  geom_rect(xmin = lwr_upr_date$lwr,xmax = lwr_upr_date$upr,ymin = lwr_upr$lwr,ymax = lwr_upr$upr,color="red",fill=NA)  +
  labs(title="Previous Week and Upcoming Prices",
       subtitle="East Denmark w/ 95% CI",
       x="Day",
       y="Price (DKK)") +
  theme(legend.position="null")

```

## Best time spans

```{r}
max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

mean_price_spot = expand.grid(start=seq(0,23,by=1),
            stop=seq(1,24,by=1)) %>% 
  filter(start<stop) %>% 
  tidyr::crossing(df) %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  filter(Hour>=start,Hour<stop) %>% 
  dplyr::summarize(SpotPriceMean=mean(SpotPriceDKK_Total_SansAfgift)) %>% 
  pull(SpotPriceMean)

expand.grid(start=seq(0,23,by=1),
            stop=seq(1,24,by=1)) %>% 
  filter(start<stop) %>% 
  tidyr::crossing(df) %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  filter(Hour>=start,Hour<stop) %>% 
  dplyr::mutate(SpotPriceMean=mean(SpotPriceDKK_Total_SansAfgift)) %>% 
  group_by(start,stop,SpotPriceMean) %>% 
  dplyr::summarize(SpotPriceDKK_Total_SansAfgift=mean(SpotPriceDKK_Total_SansAfgift,na.rm=T)) %>% 
  ggplot(aes(x=start,y=stop)) +
  geom_tile(aes(fill=SpotPriceDKK_Total_SansAfgift)) +
  scale_fill_gradient2(midpoint = mean_price_spot,low = "green",mid = "white",high = "red") +
  scale_x_continuous(breaks = seq(0,24,by=1)) +
  scale_y_continuous(breaks = seq(0,24,by=1))
```


```{r}
max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

mean_price_spot = expand.grid(start=seq(0,23,by=1),
            stop=seq(1,24,by=1)) %>% 
  filter(start<stop) %>% 
  tidyr::crossing(df) %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  filter(Hour>=start,Hour<stop) %>% 
  dplyr::summarize(SpotPriceMean=mean(SpotPriceDKK)) %>% 
  pull(SpotPriceMean)

expand.grid(start=seq(0,23,by=1),
            stop=seq(1,24,by=1)) %>% 
  filter(start<stop) %>% 
  tidyr::crossing(df) %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  filter(Hour>=start,Hour<stop) %>% 
  dplyr::mutate(SpotPriceMean=mean(SpotPriceDKK)) %>% 
  group_by(start,stop,SpotPriceMean) %>% 
  dplyr::summarize(SpotPriceDKK=mean(SpotPriceDKK,na.rm=T)) %>% 
  ggplot(aes(x=start,y=stop)) +
  geom_tile(aes(fill=SpotPriceDKK)) +
  scale_fill_gradient2(midpoint = mean_price_spot,low = "green",mid = "white",high = "red") +
  scale_x_continuous(breaks = seq(0,24,by=1)) +
  scale_y_continuous(breaks = seq(0,24,by=1))
```

```{r}
df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  ggplot(.,aes(x=Day_Num,y=Hour)) +
  geom_tile(aes(fill=SpotPriceDKK_Total)) +
  scale_fill_gradient(low = "green",high = "red") +
  scale_x_datetime(date_breaks = "7 day",date_labels = "%b %d") +
  scale_y_continuous(breaks = seq(0,23,by=1),labels = paste0(seq(0,23,by=1)," - ",seq(1,24,by=1))) +
  theme_bw()  +
  labs(title="Previous Month and Upcoming Prices",
       subtitle="East Denmark",
       x="Day",
       y="Hour") +
  theme(legend.position="null")
```

## Last Month & Upcoming

```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  ggplot(.,aes(x=Day_Num,y=Hour)) +
  geom_tile(aes(fill=SpotPriceDKK_Total)) +
  scale_fill_gradient(low = "green",high = "red") +
  scale_x_datetime(date_breaks = "7 day",date_labels = "%b %d") +
  scale_y_continuous(breaks = seq(0,23,by=1),labels = paste0(seq(0,23,by=1)," - ",seq(1,24,by=1))) +
  theme_bw()  +
  labs(title="Previous Month and Upcoming Prices",
       subtitle="East Denmark",
       x="Day",
       y="Hour") +
  theme(legend.position="null")
```

# Box plot

```{r}


max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  dplyr::mutate(Hour=factor(Hour)) %>% 
  ggplot(.,aes(x=Hour,y=SpotPriceDKK_Total_SansAfgift)) +
  geom_boxplot() +
  # geom_violin() +
  scale_y_continuous(breaks = seq(0,10,by=0.25)) +
  theme_bw()  +
  labs(title="Prices by Hour",
       subtitle="East Denmark",
       x="Day",
       y="Hour") +
  theme(legend.position="null") 
```

```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

lwr_upr = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(SpotPriceDKK_z=scale(SpotPriceDKK_Total)) %>% 
  filter(SpotPriceDKK_z<=qnorm(p = 0.975) | SpotPriceDKK_z<=qnorm(p = 0.025)) %>% 
  dplyr::summarise(lwr=min(SpotPriceDKK_Total),upr=max(SpotPriceDKK_Total))

lwr_upr_date = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::summarise(lwr=min(HourDK),upr=max(HourDK))


df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  ggplot(.,aes(x=HourDK,y=SpotPriceDKK_Total)) +
  geom_line() +
  geom_line(aes(x=HourDK,y=SpotPriceDKK_Total_SansAfgift),linetype=3) +
  geom_hline(yintercept = 0) +
  scale_y_continuous(limits=c(-1,NA),breaks = seq(-1,10,by=0.25)) +
  scale_x_datetime(date_breaks = "1 day",date_labels = "%d") +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  geom_vline(xintercept = Sys.time(),linetype=2,alpha=0.7) +
  geom_rect(xmin = lwr_upr_date$lwr,xmax = lwr_upr_date$upr,ymin = lwr_upr$lwr,ymax = lwr_upr$upr,color="red",fill=NA) +
  labs(title="Previous Month and Upcoming Prices",
       subtitle="East Denmark, with 95% CI",
       x="Day",
       y="Price (DKK)") +
  theme(legend.position="null")

```

## All Time

```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = lubridate::floor_date(min(df$HourDK),unit = "day")

lwr_upr = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(SpotPriceDKK_z=scale(SpotPriceDKK_Total)) %>% 
  filter(SpotPriceDKK_z<=qnorm(p = 0.975) | SpotPriceDKK_z<=qnorm(p = 0.025)) %>% 
  dplyr::summarise(lwr=min(SpotPriceDKK_Total),upr=max(SpotPriceDKK_Total)) %>% 
  dplyr::mutate(lwr=ifelse(lwr<0,0,lwr))

lwr_upr_date = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::summarise(lwr=min(HourDK),upr=max(HourDK))


df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  ggplot(.,aes(x=HourDK,y=SpotPriceDKK_Total)) +
  geom_line() +
  geom_smooth() +
  scale_x_datetime(date_breaks = "1 month",date_labels = "%b") +
  scale_y_continuous(limits=c(0,NA),breaks = seq(0,10,by=0.25)) +
  theme_bw() +
  theme(axis.text.x=element_text(angle=45,hjust=1)) +
  geom_vline(xintercept = Sys.time(),linetype=2,alpha=0.7) +
  geom_rect(xmin = lwr_upr_date$lwr,xmax = lwr_upr_date$upr,ymin = lwr_upr$lwr,ymax = lwr_upr$upr,color="red",fill=NA) +
  labs(title="Previous Years and Upcoming Prices",
       subtitle="East Denmark, with 95% CI",
       x="Month",
       y="Price (DKK)") +
  theme(legend.position="null") +
  geom_vline(xintercept = seq.POSIXt(ymd_hms("2015-01-01 00:00:00"),ymd_hms("2030-01-01 00:00:00"),by = "1 year"))

```

## Time Windows

```{r }

df_predict_all_week = df %>% 
  filter(HourDK >= Sys.Date()-months(6)) %>% 
  dplyr::mutate(Hour = hour(HourDK),
                Day = factor(paste0(wday(HourDK,label = TRUE)))) %>% 
  dplyr::select(SpotPriceDKK_Total_SansAfgift,Hour,Day)

train_control = caret::trainControl(method = "repeatedcv",number = 5,repeats = 5)
fit_rpart = caret::train(y = df_predict_all_week$SpotPriceDKK_Total_SansAfgift,
                         x = df_predict_all_week %>% dplyr::select(-SpotPriceDKK_Total_SansAfgift) %>% as.data.frame(),
                         method = "rpart",
                         tuneLength=50,
                         metric = "RMSE",
                         trControl = train_control)

rpart.plot(fit_rpart$finalModel)
rpart.rules(fit_rpart$finalModel)

```

```{r }

df_predict_all_week = df %>% 
  filter(HourDK >= Sys.Date()-months(6)) %>% 
  dplyr::mutate(Hour = hour(HourDK),
                Day = factor(paste0(wday(HourDK,label = TRUE)))) %>% 
  dplyr::select(SpotPriceDKK_Total,Hour,Day)

train_control = caret::trainControl(method = "repeatedcv",number = 5,repeats = 5)
fit_rpart = caret::train(y = df_predict_all_week$SpotPriceDKK_Total,
                         x = df_predict_all_week %>% dplyr::select(-SpotPriceDKK_Total) %>% as.data.frame(),
                         method = "rpart",
                         tuneLength=50,
                         metric = "RMSE",
                         trControl = train_control)

rpart.plot(fit_rpart$finalModel)
rpart.rules(fit_rpart$finalModel)

```


# Effect of reduced afgift

```{r}
expand.grid(kwh=seq(100*31)) %>% 
  dplyr::mutate(over4k=case_when(kwh>(4000/12)~kwh-(4000/12),
                                 TRUE~0)) %>% 
  dplyr::mutate(under4k=case_when(kwh<=(4000/12)~kwh,
                                 TRUE~(4000/12))) %>% 
  dplyr::mutate(afgift=0.90*under4k+0.01*over4k) %>% 
  ggplot(aes(x=kwh,y=afgift)) +
  geom_line() +
  labs(title="Monthly afgift by monthly kWh")
```

# Total kWh price by total use

```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

mean_price_spot = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  dplyr::summarize(SpotPriceMean=mean(SpotPriceDKK_Total_SansAfgift)) %>% 
  pull(SpotPriceMean)

expand.grid(kwh=seq(100*31)) %>% 
  dplyr::mutate(over4k=case_when(kwh>(4000/12)~kwh-(4000/12),
                                 TRUE~0)) %>% 
  dplyr::mutate(under4k=case_when(kwh<=(4000/12)~kwh,
                                 TRUE~(4000/12))) %>% 
  dplyr::mutate(afgift=0.90*under4k+0.01*over4k) %>% 
  dplyr::mutate(SpotPriceDKK=kwh*mean_price_spot+afgift) %>% 
  ggplot(aes(x=kwh,y=SpotPriceDKK)) +
  geom_line() +
  labs(title="Monthly afgift by monthly kWh")
```

# Total kWh price by total use (outside 17-21)

```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

mean_price_spot = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  filter(!Hour %in% c(17,18,19,20)) %>% 
  dplyr::summarize(SpotPriceMean=mean(SpotPriceDKK_Total_SansAfgift)) %>% 
  pull(SpotPriceMean)

expand.grid(kwh=seq(100*31)) %>% 
  dplyr::mutate(over4k=case_when(kwh>(4000/12)~kwh-(4000/12),
                                 TRUE~0)) %>% 
  dplyr::mutate(under4k=case_when(kwh<=(4000/12)~kwh,
                                 TRUE~(4000/12))) %>% 
  dplyr::mutate(afgift=0.90*under4k+0.01*over4k) %>% 
  dplyr::mutate(SpotPriceDKK=kwh*mean_price_spot+afgift) %>% 
  ggplot(aes(x=kwh,y=SpotPriceDKK)) +
  geom_line() +
  labs(title="Monthly afgift by monthly kWh")
```

# Average  kWh price by total use

```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

mean_price_spot = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  dplyr::summarize(SpotPriceMean=mean(SpotPriceDKK_Total_SansAfgift)) %>% 
  pull(SpotPriceMean)

expand.grid(kwh=seq(100*31)) %>% 
  dplyr::mutate(over4k=case_when(kwh>(4000/12)~kwh-(4000/12),
                                 TRUE~0)) %>% 
  dplyr::mutate(under4k=case_when(kwh<=(4000/12)~kwh,
                                 TRUE~(4000/12))) %>% 
  dplyr::mutate(afgift=0.90*under4k+0.01*over4k) %>% 
  dplyr::mutate(SpotPriceDKK=kwh*mean_price_spot+afgift) %>% 
  dplyr::mutate(SpotPriceDKK=SpotPriceDKK/kwh) %>% 
  ggplot(aes(x=kwh,y=SpotPriceDKK)) +
  geom_line() +
  labs(title="Monthly afgift by monthly kWh")
```


# Average  kWh price by total use (outside 17-12)

```{r}

max_forecast_day = lubridate::floor_date(max(df$HourDK),unit = "day")
min_forecast_day = max_forecast_day-months(1)

mean_price_spot = df %>% 
  filter(HourDK >= min_forecast_day) %>% 
  dplyr::mutate(Day_Num=lubridate::floor_date(HourDK,unit = "day"),
                Hour=lubridate::hour(HourDK)) %>% 
  filter(!Hour %in% c(17,18,19,20)) %>% 
  dplyr::summarize(SpotPriceMean=mean(SpotPriceDKK_Total_SansAfgift)) %>% 
  pull(SpotPriceMean)

expand.grid(kwh=seq(100*31)) %>% 
  dplyr::mutate(over4k=case_when(kwh>(4000/12)~kwh-(4000/12),
                                 TRUE~0)) %>% 
  dplyr::mutate(under4k=case_when(kwh<=(4000/12)~kwh,
                                 TRUE~(4000/12))) %>% 
  dplyr::mutate(afgift=0.90*under4k+0.01*over4k) %>% 
  dplyr::mutate(SpotPriceDKK=kwh*mean_price_spot+afgift) %>% 
  dplyr::mutate(SpotPriceDKK=SpotPriceDKK/kwh) %>% 
  ggplot(aes(x=kwh,y=SpotPriceDKK)) +
  geom_line() +
  labs(title="Monthly afgift by monthly kWh")
```

# Send message


```{r}

tmp_dir = tempdir()
ggsave(filename = paste0(tmp_dir,"/p1.jpg"),plot = p1,device = "jpeg")
pushoverr::pushover(message = "Electricity Forecast",attachment = paste0(tmp_dir,"/p1.jpg"))

# Best windows
msg_ = res %>% 
  dplyr::mutate(diff_hours=as.numeric(difftime(HourDK,as.POSIXct(Sys.Date()+hours(6),tz="Europe/Copenhagen"),units = "mins"))/60) %>% 
  dplyr::mutate(label_=glue("{window}H Window: {hour(HourDK)}:00 - {scales::number(rollingsum,accuracy=0.001)} DKK ({p_label}), Delay: {diff_hours}")) %>% 
  pull(label_) %>% 
  paste(.,collapse="\n")
msg_ = paste0("ELECTRICITY BEST WINDOWS:\n",msg_)
pushoverr::pushover(message = msg_)

```
