on:
  push:
     branches:
       - master
  schedule:
    - cron:  '0 21 * * *'

name: danish-electricity-prices-render

jobs:
  bookdown:
    name: renderbook
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Renviron
        run: echo $'PUSHOVER_APPKEY=${{ secrets.PUSHOVER_APPKEY }}\nPUSHOVER_USERKEY=${{ secrets.PUSHOVER_USERKEY }}' >> Renviron.site
      - name: Render Book from Action
        uses: ckrusemd/rmarkdown-action@v0.21
        with:
           input_file: index.Rmd
      - uses: actions/upload-artifact@v4
        with:
          name: _book
          path: _book/

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: _book # optional
        path: _book # optional
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _book
        user_name: 'GitHub Actions'
        user_email: ${{ secrets.EMAIL }}
        allow_empty_commit: false
        keep_files: true
        force_orphan: true
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Danish Electricity Prices - Daily Update
        to: ${{secrets.MAIL_USERNAME}}
        from: Christian Kruse
        secure: true
        body: https://ckrusemd.github.io/danish-electricity-prices/east-denmark.html

